name: Padavan固件编译

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: '选择设备型号'
        options:
        - 'B70'
        - 'BELL-A040WQ'
        - 'CR660x'
        - 'DIR-878'
        - 'DIR-882'
        - 'EA7500'
        - 'E8820V2'
        - 'GHL'
        - 'JCG-836PRO'
        - 'JCG-AC860M'
        - 'JCG-Q20-PB'
        - 'JCG-Q20'
        - 'JCG-Y2'
        - 'K2P-USB'
        - 'K2P-NANO'
        - 'K2P'
        - 'MI-4'
        - 'MI-R3G'
        - 'MI-R3P-PB'
        - 'MI-R3P-SPI'
        - 'MI-R3P'
        - 'MI-R4A'
        - 'MR2600'
        - 'MSG1500'
        - 'MSG1500-Z'
        - 'NETGEAR-BZV'
        - 'NEWIFI'
        - 'NEWIFI3'
        - 'QM-B1'
        - 'R2100'
        - 'R6800'
        - 'RE-CP-02'
        - 'RM2100'
        - 'RT-AC85P'
        - 'TX1801'
        - 'WR1200JS'
        - 'XY-C1'
        - 'ZTE-E8820S'
        - 'WE410443-TC'
        - 'WIA3300-10'
        default: 'K2P'
      release:
        type: boolean
        description: '发布到Release'
        default: 'true'

jobs:
  build:
    name: 编译-${{ inputs.target }}
    runs-on: ubuntu-latest

    steps:
      - name: 检出源码
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 必须递归拉取子模块

      - name: 安装依赖
        run: |
          sudo apt update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt install -y \
            unzip libtool-bin gperf gettext autoconf automake bison flex texinfo g++ \
            libncurses5-dev libssl-dev python3-docutils ccache \
            unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
            fakeroot kmod cpio git python3-docutils gettext automake autopoint \
            texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
            libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
          make toolchain/build
          cd toolchain-mipsel/toolchain-4.4.x
          tar cJf ../mipsel-linux-uclibc-gcc10.tar.xz *
          cp -f mipsel-linux-uclibc-gcc10.tar.xz bin/targets/
          echo "PATH=$HOME/toolchain/bin:$PATH" >> $GITHUB_ENV

      - name: 配置交叉编译链
        run: |
          cd ~
       #   wget -q https://github.com/hanwckf/padavan-toolchain/releases/download/2023-11-09/toolchain-mipsel-2023-11-09.zip
       #     unzip -q toolchain-mipsel-*.zip -d toolchain
       #     echo "PATH=$HOME/toolchain/bin:$PATH" >> $GITHUB_ENV

      - name: 编译固件
        run: |
          cd $GITHUB_WORKSPACE
          ls
          cp -f trunk/configs/templates/${{ inputs.target }}.config .config
          make -j$(nproc) all
          echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: 上传固件
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.target }}-${{ env.BUILD_DATE }}
          path: |
            bin/targets/**/*.trx  # Padavan固件输出路径
            bin/targets/**/*.txt  # 包含版本信息的文本文件

      - name: 发布到Release
        if: github.event.inputs.release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Padavan-${{ env.BUILD_DATE }}
          files: bin/targets/**/*
          body: "编译日期: ${{ env.BUILD_DATE }}\n设备型号: ${{ inputs.target }}"
